- indentation fix

diff --git a/sql-backup b/sql-backup
--- a/sql-backup
+++ b/sql-backup
@@ -137,45 +137,45 @@ for job in ${BACKUP_JOBS}; do
         continue 2
       fi
     done
-      if [ "${db_type}" = "pgsql" ]; then
-        backup_cmd="${POSTGRESQL_BIN_DIR}/pg_dump -b -Fc -h ${db_host} -p ${db_port} ${db} 2>\"${job_error_file}.log\""
-        backup_file="${BACKUP_PATH}/${db}.dump"
-        if ! test -z "${gpg_password}"; then
-          backup_cmd="${backup_cmd} | gpg -c --batch --no-tty --yes --passphrase ${gpg_password} 2>/dev/null"
-          backup_file="${backup_file}.gpg"
-        fi
-        backup_cmd="${backup_cmd} > ${backup_file}"
-        backup_file_name=$(basename "${backup_file}")
-        echo -n "  Database ${db} -> ${backup_file_name} " | tee -a "${job_log_file}"
-        eval "${backup_cmd}"
-        if test -s "${job_error_file}.log"; then
-          echo "FAILED" | tee -a "${job_log_file}"
-          cat "${job_error_file}.log" | tee -a "${job_log_file}"
-          db_fail=$((db_fail + 1))
-        else
-          echo "OK (size $(du -b "${backup_file}" 2>&1 | awk -F" " '{print $1}') bytes)" | tee -a "${job_log_file}"
-          db_ok=$((db_ok + 1))
-        fi
-      elif [ "${db_type}" = "mysql" ]; then
-        backup_cmd="mysqldump -u \"${db_user}\" -h ${db_host} -c --hex-blob --single-transaction --add-drop-database --databases ${db} 2>\"${job_error_file}.log\" | gzip 2>/dev/null"
-        backup_file="${BACKUP_PATH}/${db}.gz"
-        if ! test -z "${gpg_password}"; then
-          backup_cmd="${backup_cmd} | gpg -c --batch --no-tty --yes --passphrase ${gpg_password} 2>/dev/null"
-          backup_file="${backup_file}.gpg"
-        fi
-        backup_cmd="${backup_cmd} > ${backup_file}"
-        backup_file_name=$(basename "${backup_file}")
-        echo -n "  Database ${db} -> ${backup_file_name} " | tee -a "${job_log_file}"
-        eval "${backup_cmd}"
-        if test -s "${job_error_file}.log"; then
-          echo "FAILED" | tee -a "${job_log_file}"
-          cat "${job_error_file}.log" | tee -a "${job_log_file}"
-          db_fail=$((db_fail + 1))
-        else
-          echo "OK (size $(du -b "${backup_file}" 2>&1 | awk -F" " '{print $1}') bytes)" | tee -a "${job_log_file}"
-          db_ok=$((db_ok + 1))
-        fi
+    if [ "${db_type}" = "pgsql" ]; then
+      backup_cmd="${POSTGRESQL_BIN_DIR}/pg_dump -b -Fc -h ${db_host} -p ${db_port} ${db} 2>\"${job_error_file}.log\""
+      backup_file="${BACKUP_PATH}/${db}.dump"
+      if ! test -z "${gpg_password}"; then
+        backup_cmd="${backup_cmd} | gpg -c --batch --no-tty --yes --passphrase ${gpg_password} 2>/dev/null"
+        backup_file="${backup_file}.gpg"
       fi
+      backup_cmd="${backup_cmd} > ${backup_file}"
+      backup_file_name=$(basename "${backup_file}")
+      echo -n "  Database ${db} -> ${backup_file_name} " | tee -a "${job_log_file}"
+      eval "${backup_cmd}"
+      if test -s "${job_error_file}.log"; then
+        echo "FAILED" | tee -a "${job_log_file}"
+        cat "${job_error_file}.log" | tee -a "${job_log_file}"
+        db_fail=$((db_fail + 1))
+      else
+        echo "OK (size $(du -b "${backup_file}" 2>&1 | awk -F" " '{print $1}') bytes)" | tee -a "${job_log_file}"
+        db_ok=$((db_ok + 1))
+      fi
+    elif [ "${db_type}" = "mysql" ]; then
+      backup_cmd="mysqldump -u \"${db_user}\" -h ${db_host} -c --hex-blob --single-transaction --add-drop-database --databases ${db} 2>\"${job_error_file}.log\" | gzip 2>/dev/null"
+      backup_file="${BACKUP_PATH}/${db}.gz"
+      if ! test -z "${gpg_password}"; then
+        backup_cmd="${backup_cmd} | gpg -c --batch --no-tty --yes --passphrase ${gpg_password} 2>/dev/null"
+        backup_file="${backup_file}.gpg"
+      fi
+      backup_cmd="${backup_cmd} > ${backup_file}"
+      backup_file_name=$(basename "${backup_file}")
+      echo -n "  Database ${db} -> ${backup_file_name} " | tee -a "${job_log_file}"
+      eval "${backup_cmd}"
+      if test -s "${job_error_file}.log"; then
+        echo "FAILED" | tee -a "${job_log_file}"
+        cat "${job_error_file}.log" | tee -a "${job_log_file}"
+        db_fail=$((db_fail + 1))
+      else
+        echo "OK (size $(du -b "${backup_file}" 2>&1 | awk -F" " '{print $1}') bytes)" | tee -a "${job_log_file}"
+        db_ok=$((db_ok + 1))
+      fi
+    fi
   done
   if [ ${db_fail} -eq 0 ]; then
     job_status="OK"
