- allow backup of specified databases only

diff --git a/sql-backup b/sql-backup
--- a/sql-backup
+++ b/sql-backup
@@ -52,6 +52,7 @@ for job in ${BACKUP_JOBS}; do
     mail_from=""
     mail_name=""
     retention_days=""
+    databases=""
     excludes=""
     data_excludes=""
     report_emails=""
@@ -74,26 +75,38 @@ for job in ${BACKUP_JOBS}; do
     export PGUSER="${db_user}"
     export PGPASSWORD="${db_password}"
     POSTGRESQL_BIN_DIR=$(echo "${POSTGRESQL_BIN_DIR}" | sed -e 's/%v/'${db_version}'/' 2>/dev/null)
-    ${POSTGRESQL_BIN_DIR}/psql -q -t -h ${db_host} -p ${db_port} -c "select datname from pg_database;" template1 2>"${job_error_file}" | grep -v "template0" | sort | sed -e 's/^[ ]*//g' 1>"${job_dblist_file}"
-    if test -s "${job_error_file}"; then
-      echo "  Error reading list of databases" | tee -a "${job_log_file}"
-      cat "${job_error_file}" | tee -a "${job_log_file}"
-      rm -f "${job_error_file}" "${job_dblist_file}"
-      job_status="FAILED"
-      send_email
-      continue
+    if test -z "${databases}"; then
+      ${POSTGRESQL_BIN_DIR}/psql -q -t -h ${db_host} -p ${db_port} -c "select datname from pg_database;" template1 2>"${job_error_file}" | grep -v "template0" | sort | sed -e 's/^[ ]*//g' 1>"${job_dblist_file}"
+      if test -s "${job_error_file}"; then
+        echo "  Error reading list of databases" | tee -a "${job_log_file}"
+        cat "${job_error_file}" | tee -a "${job_log_file}"
+        rm -f "${job_error_file}" "${job_dblist_file}"
+        job_status="FAILED"
+        send_email
+        continue
+      fi
+    else
+      for db in "${databases}"; do
+        echo "${db}" >>"${job_dblist_file}"
+      done
     fi
   elif [ "${db_type}" = "mysql" ]; then
     echo "  Server type: MySQL ${db_version}" | tee -a "${job_log_file}"
     export MYSQL_PWD="${db_password}"
-    mysql -u "${db_user}" -h ${db_host} -e "show databases;" 2>"${job_error_file}" | grep -Ev "(Database|information_schema|performance_schema)" 1>"${job_dblist_file}"
-    if test -s "${job_error_file}"; then
-      echo "  Error reading list of databases" | tee -a "${job_log_file}"
-      cat "${job_error_file}" | tee -a "${job_log_file}"
-      rm -f "${job_error_file}" "${job_dblist_file}"
-      job_status="FAILED"
-      send_email
-      continue
+    if test -z "${databases}"; then
+      mysql -u "${db_user}" -h ${db_host} -e "show databases;" 2>"${job_error_file}" | grep -Ev "(Database|information_schema|performance_schema)" 1>"${job_dblist_file}"
+      if test -s "${job_error_file}"; then
+        echo "  Error reading list of databases" | tee -a "${job_log_file}"
+        cat "${job_error_file}" | tee -a "${job_log_file}"
+        rm -f "${job_error_file}" "${job_dblist_file}"
+        job_status="FAILED"
+        send_email
+        continue
+      fi
+    else
+      for db in "${databases}"; do
+        echo "${db}" >>"${job_dblist_file}"
+      done
     fi
   else
     echo "Skipping, unknown DB type ${db_type}" | tee -a "${job_log_file}"
@@ -117,24 +130,26 @@ for job in ${BACKUP_JOBS}; do
     find "${BACKUP_ROOT_DIR}/${job}" -mindepth 1 -type d -mtime +${retention_days} -exec rm -rf {} \; 1>/dev/null 2>&1
   fi
   if [ "${db_type}" = "pgsql" ]; then
-    backup_cmd="${POSTGRESQL_BIN_DIR}/pg_dumpall -g -h ${db_host} -p ${db_port} 2>\"${job_error_file}.log\" | gzip 2>/dev/null"
-    backup_file="${BACKUP_PATH}/pgsql_globals.gz"
-    if ! test -z "${gpg_password}"; then
-      backup_cmd="${backup_cmd} | gpg -c --batch --no-tty --yes --passphrase ${gpg_password} 2>/dev/null"
-      backup_file="${backup_file}.gpg"
-    fi
-    backup_cmd="${backup_cmd} > ${backup_file}"
-    backup_file_name=$(basename "${backup_file}")
-    echo -n "  PostgreSQL globals -> ${backup_file_name} " | tee -a "${job_log_file}"
-    eval "${backup_cmd}"
-    if test -f "${backup_file}"; then
-      chmod 600 "${backup_file}"
-    fi
-    if test -s "${job_error_file}.log"; then
-      echo "FAILED" | tee -a "${job_log_file}"
-      cat "${job_error_file}.log" | tee -a "${job_log_file}"
-    else
-      echo "OK (size $(du -b "${backup_file}" 2>&1 | awk -F" " '{print $1}') bytes)" | tee -a "${job_log_file}"
+    if test -z "${databases}"; then
+      backup_cmd="${POSTGRESQL_BIN_DIR}/pg_dumpall -g -h ${db_host} -p ${db_port} 2>\"${job_error_file}.log\" | gzip 2>/dev/null"
+      backup_file="${BACKUP_PATH}/pgsql_globals.gz"
+      if ! test -z "${gpg_password}"; then
+        backup_cmd="${backup_cmd} | gpg -c --batch --no-tty --yes --passphrase ${gpg_password} 2>/dev/null"
+        backup_file="${backup_file}.gpg"
+      fi
+      backup_cmd="${backup_cmd} > ${backup_file}"
+      backup_file_name=$(basename "${backup_file}")
+      echo -n "  PostgreSQL globals -> ${backup_file_name} " | tee -a "${job_log_file}"
+      eval "${backup_cmd}"
+      if test -f "${backup_file}"; then
+        chmod 600 "${backup_file}"
+      fi
+      if test -s "${job_error_file}.log"; then
+        echo "FAILED" | tee -a "${job_log_file}"
+        cat "${job_error_file}.log" | tee -a "${job_log_file}"
+      else
+        echo "OK (size $(du -b "${backup_file}" 2>&1 | awk -F" " '{print $1}') bytes)" | tee -a "${job_log_file}"
+      fi
     fi
   fi
   db_ok=0
